services:
  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/html"
    exclude_from_hc: true
    environment:
      APP_URL: ${APP_URL}
      PORT: 3000
