services:
  express_app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/var/www/html"
    ports:
      - "3000"
    environment:
      APP_URL: ${APP_URL}
      PORT: 3000
